clear:
	clear

run_01: clear
	k6 run 01_test.js

run_01_load: clear
	k6 run -u 10 -d 30s 01_test.js

run_02: clear
	k6 run 02_test.js

run_03: clear
	k6 run 03_test.js

run_04: clear
	k6 run 04_test.js